### ISSUE TITLE
First Effect link dead

### ISSUE THREAD

**Issue by freddie-freeloader** [b-studios/scala-effekt#3]
For some reason the link to [Your first effect](http://b-studios.de/scala-effekt/first-effect.html) is dead. :cry: 

All other links seem to work though.

**Comment by b-studios** [comment]
Oh yes, that is true. The page has been moved to [guides/getting-started](http://b-studios.de/scala-effekt/guides/getting-started.html).

Can you point me to the page that contains the broken link?

**Comment by b-studios** [comment]
Ah, I see. It is still in README.md. Do you want to fix that? This will make a great PR ;)

**Comment by b-studios** [comment]
Closed by #4
