### ISSUE TITLE
Can not import the library with sbt

### ISSUE THREAD

**Issue by Oxymora** [b-studios/scala-effekt#7]
Hello, 

libraryDependencies += "de.b-studios" %% "effekt" % "0.3-SNAPSHOT"  does not work.

The modul wasn't found, so maybe the repo
https://repo1.maven.org/maven2/de/b-studios/scala-effekt_2.12/0.3-SNAPSHOT/scala-effekt_2.12-0.3-SNAPSHOT.pom
is down?

**Comment by freddie-freeloader** [comment]
Hey @Oxymora!

You can find the module on Sonatype:
https://oss.sonatype.org/content/repositories/snapshots/de/b-studios/effekt_2.12/0.3-SNAPSHOT/effekt_2.12-0.3-SNAPSHOT.pom

`sbt` won't discover this per default unless you adjust it accordingly:
```scala
resolvers += 
  "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"
```

After this, `libraryDependencies += "de.b-studios" %% "effekt" % "0.3-SNAPSHOT"` should be resolved properly. :slightly_smiling_face: 

See: https://www.scala-sbt.org/1.x/docs/Resolvers.html

**Comment by kschwarz1116** [comment]
It would be nice to reopen this as an issue that the documentation needs to be updated; I had to go down this same path.
